name: Desktop Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build Desktop (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    defaults:
      run:
        working-directory: apps/desktop

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            apps/desktop/package-lock.json

      - name: Install deps
        run: npm ci

      - name: TypeScript build
        run: npm run build

      - name: Build & Publish artifacts to GitHub Releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # For unsigned builds on CI (macOS notarization not configured)
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
        run: npm run dist -- --publish always

      - name: Upload dist as workflow artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ matrix.os }}-artifacts
          path: apps/desktop/release/**/*
          if-no-files-found: ignore
