name: "Kilo – Verify Pull Request"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Validate PR title follows Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm ci

      - name: Lint commit messages on this branch  
        run: |
          npm install --no-save @commitlint/config-conventional @commitlint/cli
          echo "module.exports={extends:['@commitlint/config-conventional']}" > commitlint.config.js
          git log --format=%B ${{ github.event.pull_request.base.sha }}...HEAD | npx commitlint
